### PR TITLE
Manually require application controller to overwrite Rails autoloading

### PR DESCRIPTION
**Pull request by mikeastock**
We were having an issue where in our application the Rails engine was loading our `ApplicationController` and not resque-web's. I don't know if this is the best solution but it solved our problem.

### CODE REVIEW

**Comment by mcfiredrill** [comment]
@mikeastock can you let me know if #79 fixes the problem? If so I will definitely merge that.

**Comment by mrhead** [comment]
@mcfiredrill I am @mikeastock colleague and I can confirm that #79 fixes our issues.

**Comment by mcfiredrill** [comment]
@mrhead great! I'm going to merge #79 then and hope for the best. Sorry I do not currently use resque heavily so I cannot thoroughly test this, but I'm trying my best to help since I have commit access to this project.

I can release a new Gem version soon as well.

**Comment by mikeastock** [comment]
@mcfiredrill thanks so much!

**Pull request closed without merging**
