### PR TITLE
Include css and js from plugins if they are there (without updated gems)

### PR DESCRIPTION
**Pull request by mattgibson**
This is a cleaner version of https://github.com/resque/resque-web/pull/85, but without the updated gems.

### CODE REVIEW

**Comment by mattgibson** [comment]
Hmm. Looks like it needs the gems updated for 2.2

**Comment by mcfiredrill** [comment]
@mattgibson Thank you for doing this. :yellow_heart: 

I see, perhaps you could make a PR to fix the Gems to pass on 2.2? 
After that is merged, you (and other people with currently failing PRs) could rebase.

**Comment by mcfiredrill** [comment]
@mattgibson now that we merged your other PR for the Gems, could you rebase this PR?

**Comment by mcfiredrill** [comment]
Not sure what the coveralls failure is about really, but this looks good.
Anyone else out there wanna :+1: this ?

**Comment by kirillplatonov** [comment]
@mattgibson Hi. Great job! 👏

Thinking about loading plugin's assets - not all plugins has its own assets. With `stylesheet_link_tag` and `javascript_include_tag ` it will generate an error. Here's example with resque-scheduler plugin:
Example

I think we need to think about this problem together. Could you give the link to the plugin, for which try to load assets, please?

**Comment by mattgibson** [comment]
@kirillplatonov Yes, this occurred to me too. I will see if I can add a file_exists check of some sort.

**Comment by kirillplatonov** [comment]
@mattgibson Probably `Rails.application.assets.find_asset("application.css")` will help?

**Comment by kirillplatonov** [comment]
Looks fine now :+1:

**Comment by mattgibson** [comment]
Thanks. There's no tests for this, but I'm not sure of the best way of testing, or even if it's desirable. The plugins are in separate gems, so would it need a dummy gem of some sort?

**Comment by mcfiredrill** [comment]
@mattgibson @kirillplatonov 
Thanks guys, seems good to merge now.

In the future, perhaps a test plugin (it doesn't have to actually do anything) could be added to the existing tests/test dummy app.

**Pull request merged**
