### PR TITLE
all controllers should be extending ResqueWeb::ApplicationController ins...

### PR DESCRIPTION
**Pull request by jdatti**
...tead of parent application's ::ApplicationController

### CODE REVIEW

**Comment by jdatti** [comment]
This pull request fixes 
https://github.com/resque/resque-web/issues/76

**Comment by flynfish** [comment]
:+1: would love to see this merged!

**Comment by mcfiredrill** [comment]
Hi I'm pretty sure this is the right thing to do, but I'm not really using Resque or ResqueWeb these days and don't really have time to test. Can anyone test this an confirm it fixes the issues like https://github.com/resque/resque-web/issues/76 and maybe others?

**Comment by mcfiredrill** [comment]
If a few people can confirm this is working, I will merge it.

**Comment by mcfiredrill** [comment]
This appears to solve a number of issues, I haven't tested it thoroughly as I'm not currently much of a  resque user. However I want to help out if I can since I have commit access to this project. 

I'm going to merge this and release a new Gem version soon. Cheers!

**Comment by rarruda** [comment]
It would be nice with a new release / new Gem version! I'm probably not the only one who could benefit from this bugfix! :smile:

**Comment by mcfiredrill** [comment]
@rarruda Oh sorry, I thought I did. I'll make a release today.

**Pull request merged**
