### PR TITLE
Add 'Return To Application' Link to Menu Bar

### PR DESCRIPTION
**Pull request by msimkins**
This adds a return to Application link to the Menu bar to enable you to return to the root path of the main application

### CODE REVIEW

**Comment by kirillplatonov** [comment]
@msimkins Hello. Thanks for that PR, nice work! Could you please resolve conflicts in `Gemfile.lock`? I'd like to merge this PR.

**Comment by msimkins** [comment]
@kirillplatonov I believe this should now merge correctly

**Comment by msimkins** [comment]
@kirillplatonov Did you want to merge this, or do you need further work

**Comment by kirillplatonov** [comment]
@msimkins Yes, I will merge it soon. Just still not have enough time for that project. Everything is great, thanks for this fixes!

**Pull request merged**
