### PR TITLE
Fix current tab checking

### LINKED ISSUE #74: Navigation menu are not highlighting when clicking
Navigation menu are not highlighting when clicking a specific link (ex. Overview, Working, Failures, etc.). This is the screen shoot of my screen.

I used resque-web master branch with twitter bootstrap 2. Please solve it.

### PR DESCRIPTION
**Pull request by kirillplatonov**
Fixes #74. Works both with internal tabs and external plugins tabs.

### CODE REVIEW

**Comment by mcfiredrill** [comment]
I'm not really sure if this or the gsub solution in #75 is better. Any thoughts @dark-prince?

**Comment by kirillplatonov** [comment]
@mcfiredrill My mistake. I need to give an explanation of reason.

With gsub solution everything is fine, except that it works only with internal tabs.
For example for resque-sheduler-web plugin `params[:controller]` will be `resque_web/plugins/resque_scheduler/schedules`

That's why I match path, not controller name.

**Comment by kirillplatonov** [comment]
@mcfiredrill could you merge it?

**Comment by mcfiredrill** [comment]
Seems good to me. Merging unless anyone has any objections?

**Comment by kirillplatonov** [comment]
@mcfiredrill let's merge it?)

**Comment by kirillplatonov** [comment]
@mcfiredrill Hi. As I already mentioned #75 will works only with internal tabs. Tabs from plugins will not be highlighted =( Example from one of my projects:
Internal tab https://www.dropbox.com/s/i9wirqcq09nc035/Screenshot%202015-12-20%2012.23.00.png?dl=0
External tab https://www.dropbox.com/s/taqtkxxosmq0viu/Screenshot%202015-12-20%2012.23.21.png?dl=0

So I reopened my PR which fixes that.

**Comment by mcfiredrill** [comment]
@kirillplatonov Ah right, I remember the discussion now. I will merge this. I wasn't sure why you closed it. Thanks for reminding me.

**Pull request merged**
