### PR TITLE
fixed font awesome bug that arises when you updated gemfile

### PR DESCRIPTION
**Pull request by lemuelbarango**
fixed font awesome bug that arises when you updated twitter-bootstrap-rails gem

### CODE REVIEW

**Comment by grosser** [comment]
@kirillplatonov also ran into that :<

**Comment by kirillplatonov** [comment]
@lemuelbarango thanks for your pull request. I will check whats going on with master tests today and will merge with PR.

**Comment by seanlinsley** [comment]
As of this PR I'm now getting this error:
```
Sass::SyntaxError at /

File to import not found or unreadable: font-awesome-sprockets.
```

I'm using twitter-bootstrap-rails 4.0.0.

Looks like Font Awesome was actually removed from the gem: https://github.com/seyhunak/twitter-bootstrap-rails/issues/889

**Comment by seanlinsley** [comment]
For now I'm going to stick with twitter-bootstrap-rails 3.2.2.

**Comment by kirillplatonov** [comment]
@seanlinsley this issue fixed in master now. I will prepare release in next few days

**Pull request merged**
