### PR TITLE
use image_tag and asset_tag helpers everywhere

### LINKED ISSUE #37: Assets
After I deploy resque-web to Heroku and visit resque-web I get the following errors.

`ActionController::RoutingError (No route matches [GET] "/images/working.png"):`

I can see that the assets are in https://github.com/resque/resque-web/tree/master/app/assets/images/resque_web but I wonder if something else needs to be configured in the Engine config itself. E.g. http://guides.rubyonrails.org/asset_pipeline.html#adding-assets-to-your-gems

I don't have much experience with Engines myself just wondering if anyone knows what could be the problem here.

### PR DESCRIPTION
**Pull request by mcfiredrill**
fixes #37

### CODE REVIEW

**Comment by chrishough** [comment]
I am still seeing this error when attempting to use resque_web without the asset pipeline

**Comment by mcfiredrill** [comment]
@chrishough Why are you using resque_web without the asset pipeline?

**Comment by chrishough** [comment]
it is a rails application running as an API.  It is odd that it requires : 
```
Rails.application.config.assets.precompile += %w(resque_web/*.png) if AppSettings.settings[:mount_resque_web]
``` 
at all, right?

**Comment by mcfiredrill** [comment]
This project is a rails engine.

If you have to add that line to your app, then yes that's a bug. :)

**Comment by chrishough** [comment]
That is what I was thinking. Should we re-open this one or create a new one?

**Comment by mcfiredrill** [comment]
This is a pull request so opening a new issue sounds good. Please search the existing issues to see if someone else has the same issue, if you haven't already.

**Comment by chrishough** [comment]
@mcfiredrill as requested I just created a bug for this in a new issue.

**Pull request merged**
