### PR TITLE
Add job ID to Queue show and Job Failure page

### PR DESCRIPTION
**Pull request by omarqureshi**

### CODE REVIEW

**Comment by kiyanwang** [comment]
What happens if the id is not set?  i think we saw yesterday that payload['id'] is set by the php-resque framework but not by ruby / node ... does this take that into account?

**Comment by omarqureshi** [comment]
Nil.to string is the empty string. So should be ok

On 23 Sep 2016 7:10 a.m., "Nadeem Shabir" <notifications@github.com> wrote:

What happens if the id is not set? i think we saw yesterday that
payload['id'] is set by the php-resque framework but not by ruby / node ...
does this take that into account?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/resque/resque-web/pull/120#issuecomment-249110929>, or mute
the thread

**Comment by kiyanwang** [comment]
> Nil.to string is the empty string. So should be ok

awesome

👍

**Comment by kirillplatonov** [comment]
@omarqureshi thanks for your PR. Nice job! It's merged in master now and I will release it with new version soon.

**Pull request merged**
